name: Build and Test GitHub Action

on: push

jobs:
  build_and_test:
    name: Build and test the GitHub Action
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        dotnet: [ '3.1.100' ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v1

    - name: Run the private action
      id: consoleapp
      uses: ./
      with:
        name: Live Coding

    - name: Get the output
      shell: bash
      run: |
        echo ${{ steps.consoleapp.outputs.greeting }}

